version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: proyecto_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: iluminacion_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/bd.sql:/docker-entrypoint-initdb.d/bd.sql:ro

  backend:
    build:
      context: ./backend
    container_name: proyecto_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret123
      DB_NAME: iluminacion_db
      FLASK_ENV: production
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - db
      - ollama
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://3.225.75.42:5000
    container_name: proyecto_frontend
    restart: unless-stopped
    ports:
      - "4173:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: proyecto_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      OLLAMA_CONTEXT_LENGTH: 1024
      OLLAMA_NUM_PARALLEL: 1
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data: