CREATE DATABASE IF NOT EXISTS iluminacion_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE iluminacion_db;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  correo VARCHAR(150) NOT NULL UNIQUE,
  rol VARCHAR(50) NOT NULL DEFAULT 'usuario',
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE actividades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT,
  lux_minimo INT,
  lux_maximo INT,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE salones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  ubicacion VARCHAR(150),
  descripcion TEXT,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE configuracion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  modo_automatico BOOLEAN NOT NULL DEFAULT TRUE,
  intensidad_led_default INT NOT NULL DEFAULT 70,
  umbral_lux INT NOT NULL DEFAULT 300,
  max_consumo FLOAT NOT NULL DEFAULT 100.0,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sensores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lux FLOAT NOT NULL,
  intensidad_led INT NOT NULL,
  consumo_energetico FLOAT NOT NULL,
  modo_automatico BOOLEAN NOT NULL,
  actividad_id INT,
  salon_id INT NOT NULL,
  registrado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (actividad_id) REFERENCES actividades(id) ON DELETE SET NULL,
  FOREIGN KEY (salon_id) REFERENCES salones(id) ON DELETE CASCADE
);

CREATE TABLE historial_iluminacion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sensor_id INT NOT NULL,
  lux FLOAT NOT NULL,
  intensidad_led INT NOT NULL,
  consumo_energetico FLOAT NOT NULL,
  modo_automatico BOOLEAN NOT NULL,
  actividad_id INT,
  registrado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (sensor_id) REFERENCES sensores(id) ON DELETE CASCADE,
  FOREIGN KEY (actividad_id) REFERENCES actividades(id) ON DELETE SET NULL
);

CREATE TABLE consumo_energetico (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sensor_id INT NOT NULL,
  total_kwh FLOAT NOT NULL,
  periodo_inicio DATE NOT NULL,
  periodo_fin DATE NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (sensor_id) REFERENCES sensores(id) ON DELETE CASCADE
);
