# Default configuration constants (match ESP32 firmware defaults)
DEFAULT_UMBRAL_LUX = 100
DEFAULT_INTENSIDAD_LED_DEFAULT = 80
DEFAULT_PWM_ALTO = 160
DEFAULT_MAX_CONSUMO = 100.0
DEFAULT_MODO_AUTOMATICO = True
